### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by antonmry** [vigojug/vigojug#1]
## Pendentes

(Cousas que non chegan a Issue pero que se nos poden escapar ou que podemos discutir antes plasmarlas nunha issue)

- [x] Coordinarse con outros JUGs
- [ ] Buscar colaboración empresas locais
- [ ] Publicitar en outros foros (GDGVigo, etc.) pero sen facer spam
  - [x] XantarDev
  - [ ] GDGVigo -> pendente Banner!
  - [x] PHPVigo
  - [x] JSVigo
  - [x] PythonVigo

**Outros (añadir como comentario e vou actualizando aquí)**

## Feitos

- [x] Reserva Kaleido Coworking unha vez o mes
- [x] Montar unha web 
- [x] hacer el logo - hecho
- [x] Falar co PHPVigo o tema de slack - canal #vigojug
- [x] Mover o twitter => doy por bueno :)
- [x] Planificar próximas charlas => https://github.com/vigojug/vigojug/issues/2
- [x] Conseguir licencias de IntelliJ para sortear (preguntar PHPVigo?) => https://github.com/vigojug/vigojug/issues/5

**Comment by rubenrua** [comment]
Conseguir licencias de IntelliJ para sortear?? Ver PHP Vigo?
